/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Orange(props) {
    const { nodes, materials } = useGLTF("./models/orange.glb");
    return (
        <group { ...props } dispose={ null }>
            <mesh
                name="orange"
                castShadow
                receiveShadow
                geometry={ nodes.Heta1__mPltFruitOrange02.geometry }
                material={ materials.mPltFruitOrange02 }
                scale={ 0.03 }
            />
        </group>
    );
}

useGLTF.preload("./models/orange.glb");
